In [1]:
import numpy as np

In [2]:
# 生成随机数组
data = np.random.randn(10)

In [3]:
# 查看数据
data

array([ 0.22679784,  1.7904428 ,  0.30575312,  1.47957756,  0.16784041,
        0.67751505,  0.93379422, -0.13666222, -0.23959557,  0.16239198])

In [4]:
# 数组运算
data + data

array([ 0.45359568,  3.5808856 ,  0.61150624,  2.95915513,  0.33568082,
        1.35503009,  1.86758844, -0.27332443, -0.47919114,  0.32478395])

In [5]:
data * 10

array([ 2.26797838, 17.90442798,  3.05753121, 14.79577563,  1.67840408,
        6.77515047,  9.33794219, -1.36662216, -2.39595568,  1.62391976])

In [6]:
# 创建数组对象
data1 = [3, 4, 5, 6, 7, 8]
arr1 = np.array(data1)

In [7]:
# 查看数组类型
type(arr1)

numpy.ndarray

In [8]:
# 查看数组内容
arr1

array([3, 4, 5, 6, 7, 8])

In [9]:
# 二维数组
data2 = [
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10]
]
arr2 = np.array(data2)

In [10]:
# 查看数组
arr2

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [11]:
# 查看数组维度
arr2.ndim

2

In [12]:
# 查看数组形状
arr2.shape

(2, 5)

In [13]:
# 查看数据类型
arr2.dtype

dtype('int64')

In [14]:
# 转换为浮点数数组
arr3 = arr2.astype("float")

In [15]:
arr3

array([[ 1.,  3.,  5.,  7.,  9.],
       [ 2.,  4.,  6.,  8., 10.]])

In [16]:
arr3.dtype

dtype('float64')

In [19]:
from enum import Enum
class Interval(Enum):
    """K线周期"""
    MINUTE_1 = "1m"
    MINUTE_5 = "5m"
    MINUTE_15 = "15m"
    MINUTE_30 = "30m"
    HOUR_1 = "1h"
    HOUR_4 = "4h"
    HOUR_6 = "6h"
    HOUR_12 = "12h"
    DAY_1 = "1d"
    WEEK_1 = "1w"
    MONTH_1 = "1M"

In [23]:
from datetime import datetime, timedelta
batch_sizes = {
    Interval.MINUTE_1: timedelta(days=1),  # 1分钟数据，1天一批
    Interval.MINUTE_5: timedelta(days=7),  # 5分钟数据，7天一批
    Interval.MINUTE_15: timedelta(days=30),  # 15分钟数据，30天一批
    Interval.MINUTE_30: timedelta(days=60),  # 30分钟数据，60天一批
    Interval.HOUR_1: timedelta(days=90),  # 1小时数据，90天一批
    Interval.HOUR_4: timedelta(days=180),  # 4小时数据，180天一批
    Interval.HOUR_6: timedelta(days=365),  # 6小时数据，365天一批
    Interval.HOUR_12: timedelta(days=365),  # 12小时数据，365天一批
    Interval.DAY_1: timedelta(days=365 * 2),  # 日线数据，2年一批
    Interval.WEEK_1: timedelta(days=365 * 5),  # 周线数据，5年一批
    Interval.MONTH_1: timedelta(days=365 * 10),  # 月线数据，10年一批
}

In [25]:
Interval.HOUR_1

<Interval.HOUR_1: '1h'>

In [26]:
interval = Interval.HOUR_1
batch_sizes.get(interval)

datetime.timedelta(days=90)

In [28]:
a = batch_sizes.get(interval.value)

In [29]:
a