In [1]:
# 用CSV模块加载数据
from csv import DictReader

with open("BTC_close.csv") as f:
    reader = DictReader(f)
    close_data = [row["close"] for row in reader]

In [2]:
# 查看前10个数据
close_data[:10]

['118351.0',
 '118312.14',
 '118312.14',
 '118327.16',
 '118303.49',
 '118316.0',
 '118370.99',
 '118363.07',
 '118336.68',
 '118246.59']

In [3]:
# 转换为数组
import numpy as np

close_array = np.array(close_data).astype("float")

In [4]:
# 取最后20个元素
sample_array = close_array[-20:].copy()

In [5]:
# 查看sample_array
sample_array

array([116846.48, 116852.02, 116852.02, 116813.85, 116791.95, 116836.38,
       116836.38, 116827.46, 116835.39, 116836.39, 116836.39, 116848.07,
       116856.23, 116831.13, 116831.12, 116851.99, 116836.72, 116858.81,
       116892.47, 116947.15])

In [6]:
# 四则运算（这里以加法为例）
sample_array + sample_array

array([233692.96, 233704.04, 233704.04, 233627.7 , 233583.9 , 233672.76,
       233672.76, 233654.92, 233670.78, 233672.78, 233672.78, 233696.14,
       233712.46, 233662.26, 233662.24, 233703.98, 233673.44, 233717.62,
       233784.94, 233894.3 ])

In [7]:
# 数组每个元素乘以10
sample_array * 10

array([1168464.8, 1168520.2, 1168520.2, 1168138.5, 1167919.5, 1168363.8,
       1168363.8, 1168274.6, 1168353.9, 1168363.9, 1168363.9, 1168480.7,
       1168562.3, 1168311.3, 1168311.2, 1168519.9, 1168367.2, 1168588.1,
       1168924.7, 1169471.5])

In [8]:
# 数组每个元素除以1000
sample_array / 1000

array([116.84648, 116.85202, 116.85202, 116.81385, 116.79195, 116.83638,
       116.83638, 116.82746, 116.83539, 116.83639, 116.83639, 116.84807,
       116.85623, 116.83113, 116.83112, 116.85199, 116.83672, 116.85881,
       116.89247, 116.94715])

In [9]:
# 计算均值
sample_array.mean()

np.float64(116845.92)

In [10]:
# 计算中位数
np.median(sample_array)

np.float64(116836.555)

In [11]:
# 计算最大值
sample_array.max()

np.float64(116947.15)

In [12]:
# 计算最小值
sample_array.min()

np.float64(116791.95)

In [13]:
# 计算标准差
sample_array.std()

np.float64(30.068298920955367)

In [14]:
# 累积求和
np.cumsum(sample_array)

array([ 116846.48,  233698.5 ,  350550.52,  467364.37,  584156.32,
        700992.7 ,  817829.08,  934656.54, 1051491.93, 1168328.32,
       1285164.71, 1402012.78, 1518869.01, 1635700.14, 1752531.26,
       1869383.25, 1986219.97, 2103078.78, 2219971.25, 2336918.4 ])

In [16]:
data2 = [
    [1, 3, 5, 7, 9],
    [2, 4, 6, 8, 10]
]
arr2 = np.array(data2)

In [17]:
arr2

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [18]:
arr2[1][2]

np.int64(6)

In [19]:
arr2[1, 2]

np.int64(6)

In [20]:
index = arr2 > 3

In [21]:
index

array([[False, False,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [22]:
arr2[arr2 > 3]

array([ 5,  7,  9,  4,  6,  8, 10])